using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Xml;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonogameLibrary.UI.Base;
using MonogameLibrary.UI.Elements;

namespace ZoFo.GameCore.GUI;

public class InventoryGUI : AbstractGUI
{
    protected override void CreateUI()
    {
        // int width = AppManager.Instance.inGameHUDHelperResolution.X;
        // int height = AppManager.Instance.inGameHUDHelperResolution.Y;
    }

    public override void Update(GameTime gameTime)
    {
        
    }
}